### ISSUE TITLE
Needs more cowbell.

### ISSUE THREAD

**Issue by Infamoustrey** [zred/iam#1]
This is a great framework but personally I expect my python libraries to include a lot more cowbell, like a lot more. All of FAANG has cowbell and many medium to large businesses include cowbell so I feel like decently sized frameworks like this should include cowbell.

Until more cowbell is added I'll be making the switch to the `youaint` framework [here](https://github.com/Infamoustrey/youaint). I'll be happy to switch back once this repo includes some gosh damn cowbell

**Comment by zred** [comment]
more cowbell added, issue closed
